name: Deployment Kubernetes

on:
  workflow_call:
    secrets:
      KUBE_CONFIG:
        required: true
  workflow_dispatch:

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create ConfigMap
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes/hvac-config.yml
      - name: Create Secrets
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes/hvac-secrets.yml
      - name: Create Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes/hvac-deployment.yml
      - name: Create Service
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./kubernetes/hvac-service.yml
